# Generated by Django 5.0.1 on 2024-01-26 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
