# Generated by Django 5.0.1 on 2024-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='priority',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
