version: "3"
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
        restart: on-failure
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    api:
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            - DJANGO_SECRET_KEY=django-insecure-6tknbbhf05qe01%u380w^f&p(0^v8w^f0ue-)u89ofp764tyy=
            - DEBUG=True
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres_password
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - TWILIO_ACCOUNT_SID=
            - TWILIO_AUTH_TOKEN=
            - TWILIO_FROM_PHONE_NUMBER=
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        restart: on-failure
        depends_on:
            - postgres
    cron:
        build:
            dockerfile: Dockerfile.cron
            context: .
        environment:
            - DJANGO_SECRET_KEY=django-insecure-6tknbbhf05qe01%u380w^f&p(0^v8w^f0ue-)u89ofp764tyy=
            - DEBUG=True
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres_password
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - TWILIO_ACCOUNT_SID=
            - TWILIO_AUTH_TOKEN=
            - TWILIO_FROM_PHONE_NUMBER=
        volumes:
            - ./:/app
        restart: on-failure
        depends_on:
            - postgres
            - api
